image: docker:stable
services:
- docker:dind

stages:
- build
- test
- release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/ansible-playbook:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/ansible-playbook:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    - docker push "$CONTAINER_TEST_IMAGE"

test:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE --version
    - docker run --entrypoint "" $CONTAINER_TEST_IMAGE python -c 'import pycurl; print(pycurl.version)'
    - docker run --entrypoint "" $CONTAINER_TEST_IMAGE python -c 'import pyaem; print(pyaem.__version__)'

release-image:
  stage: release
  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master
